### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by agius** [hired/stretchy#4]
Coming up on the ole' to-do list:
- [X] Finish up #29 "simplification" to make the rest of these easier to implement.
- [x] Cleanup fro said PR:
  - [x] Figure out how `.boost.query` and `.boost.filter` should work, implement
  - [x] Handle `.match(things: [thing1, thing2])`
  - [x] ~~YARDocs~~ :football: punted! got a better idea
  - [x] Figure out why `api2.filter(or: [api1.filter_node.json])` is returning a filtered query instead of a plain ol' filter
  - [x] ~~Extract `root: {}` options from `Api#initialize` (ie, `index:` and `type:`~~ Doesn't actually make anything any better
- [x] Scopes similar to ActiveRecord's
  - Do we also need to implement something like `include Stretchy::Searchable` to handle cases like this?
  - Any way to avoid creating new clause classes at runtime? I hate dynamically-defined classes XD
- [x] Multi-type / multi-index queries (need to figure out how to set up these queries in a chainable way)
- [x] Allow passing raw JSON to `.where` , `.match` , etc to make dealing with new & unsupported queries easier
- [x] support passing in objects as [Nested queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html) or in dot notation
  - Stretchy doesn't do mapping / indexing, so it won't know whether `type: :nested` or `include_in_parent` are set. Perhaps pass `nested: true` to the method? Or allow passing mapping info to Stretchy?
- [ ] Suggester support
- [x] [Elasticsearch 2.0 compatibility](https://www.elastic.co/blog/release-we-have)
- [ ] Better aggregations and suggesters as chainable methods
- [ ] Jekyll docs
- [ ] `or` queries with [DisMax Queries](http://www.elastic.co/guide/en/elasticsearch/reference/0.90/query-dsl-dis-max-query.html) / [Or Filters](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-or-filter.html)
  - probably similar to [ActiveRecord's new .or() method](https://github.com/rails/rails/blob/master/activerecord/test/cases/relation/or_test.rb) (rails5)
- [ ] Support passing API objects to other APIs to be used as nested queries (see below)

``` ruby
api1 = search.match(phrase: 'hello')
api2 = search.match(name: "susan", child_doc: api1)
# returns
{query: {bool: {must: [
  {match: {name: 'susan'}},
  {nested: {
    path: :child_doc,
    query: {
      'child_doc.phrase' => 'hello'
    }  
  }}
]}}}
```

**Comment by christospappas** [comment]
What are your thoughts on this syntax for nested aggregations? There's a bit of repetition but at least it's clear.

```
aggs(:in_current_auction).where({})
  .nest(:in_current_auction).aggs(:bucket_ids).where({})
  .nest(:in_current_auction).aggs(:location_bucket_ids).where({})
.aggs(:just_for_you).where({})
```

**Comment by agius** [comment]
Hmmm... looks solid at first glance. I think we should implement non-nested aggregations for v0.3, then make a branch for this and try it out in specs. See how confusing it gets when the aggregations get _really_ complicated.

**Comment by jkarmel** [comment]
My two cents

The ability to pass raw JSON is by far the most important item in this list - adding that adds every feature elastic has.

**Comment by hrp** [comment]
It'd be cool to see query string query (https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-query-string-query.html). Is there a way to instantly support everything via method-missing or something?

**Comment by agius** [comment]
Frankly, I don't think we should allow query strings, for the [reasons stated here](https://www.elastic.co/guide/en/elasticsearch/guide/current/search-lite.html).

> However, you can also see that its terseness can make it cryptic and difficult to debug. And it’s fragile—a slight syntax error in the query string, such as a misplaced -, :, /, or ", and it will return an error instead of results.
> 
> Finally, the query-string search allows any user to run potentially slow, heavy queries on any field in your index, possibly exposing private information or even bringing your cluster to its knees!
> 
> **TIP:** For these reasons, we don’t recommend exposing query-string searches directly to your users, unless they are power users who can be trusted with your data and with your cluster.

**Comment by hrp** [comment]
Oh interesting! You've clearly thought about this. Could potentially enable it in for Admin or use Stretchy to scrub the query (if possible at all). Regardless, cool! :sunglasses:

**Comment by agius** [comment]
Yeah, I was thinking about adding a query string parser to break into component parts, but it's a huge challenge. There's a lot of ambiguity in giving a query language to users:

```
"my string" AND type:doctor OR booster~10
{
  dis_max: {
    boost: 10,
    queries: [
      { 
        filtered: {
          query: { 
            match: { 
              query: "my string", 
              operator: "and" 
            }
          }
        },
        filter: { 
          term: { 
            type: 'doctor' 
          }
        }
      },
      {
        match: {
          '_all' : 'booster'
        }
      }
    ]
  }
}

but of course, that could be wrong. the use may have meant:

{
  filtered: {
    query: { 
      match: { 
        query: "my string", 
        operator: "and" 
      }
    }
  },
  filter: {
    or: {
      term: {
        type: 'doctor' 
      },
      {
        query: {
          match: {
            '_all' : 'booster'
          }
        }
      }
    }
  }
}
```
Obviously Lucene + Elastic have defaults here, but referring your users to technical docs is a non-starter.

Ultimately, I think it's best to find ways to return the right results without having to ask the user to learn some query language. Remember AltaVista? I loved them because I could specify in clear, logical terms what I wanted it to return. I laughed at Google because it seemed too simple to work. Then it crushed AltaVista.

I do appreciate the suggestion, though! Definitely worth some consideration as part of supporting as much of Elastic's API as possible. First word on my comment shoulda been "Thanks!" :smile_cat:

**Comment by ultrasaurus** [comment]
sorting would be nice!

**Comment by agius** [comment]
BTW for everyone - making some progress as time goes on :smile_cat: Updated the roadmap to reflect current plans & priorities

**Comment by agius** [comment]
This is all pretty outdated, and now Github has real-ish projects support. Gonna close for now and work out what the next few things are.
